project:
  type: website
  output-dir: _site

website:
  title: "Sannakate"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: projects/index.qmd
        text: Projects
      - href: notes/index.qmd
        text: Notes

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: false
    page-layout: article

    include-in-header:
      - text: |
          <script data-goatcounter="https://yourcode.goatcounter.com/count"
                  async src="//gc.zgo.at/count.js"></script>
